export const CARDS = [
    {
        level: 'swimmer2',
        session: 'Summer',
        day: 'Wed',
        time: '12:30',
        year: '2024',
        createdOn: 'July 5 2023',
    },
    {
        level: 'swimmer2',
        session: 'Summer',
        day: 'Wed',
        time: '12:30',
        year: '2024',
        createdOn: 'July 5 2023',
    },
    {
        level: 'swimmer2',
        session: 'Summer',
        day: 'Wed',
        time: '12:30',
        year: '2024',
        createdOn: 'July 5 2023',
    },
    {
        level: 'swimmer2',
        session: 'Summer',
        day: 'Wed',
        time: '12:30',
        year: '2024',
        createdOn: 'July 5 2023',
    },
    {
        level: 'swimmer2',
        session: 'Summer',
        day: 'Wed',
        time: '12:30',
        year: '2024',
        createdOn: 'July 5 2023',
    },
    {
        level: 'swimmer2',
        session: 'Summer',
        day: 'Wed',
        time: '12:30',
        year: '2024',
        createdOn: 'July 5 2023',
    },
    {
        level: 'swimmer2',
        session: 'Summer',
        day: 'Wed',
        time: '12:30',
        year: '2024',
        createdOn: 'July 5 2023',
    },
    {
        level: 'swimmer2',
        session: 'Summer',
        day: 'Wed',
        time: '12:30',
        year: '2024',
        createdOn: 'July 5 2023',
    },
    {
        level: 'swimmer2',
        session: 'Summer',
        day: 'Wed',
        time: '12:30',
        year: '2024',
        createdOn: 'July 5 2023',
    },   
];