export type SkillDescription = string[];

const PARENT_AND_TOT_1_SKILLS: SkillDescription = [
	'Enter and exit the water safely with tot',
	'Readiness for submersion',
	'Hold tot on front, eye contact',
	'Hold tot on back, head and back support',
	'Front float (face out) - assisted',
	'Back float (assisted)',
	'Float wearing PFD (assisted)',
	'Arms splashing, reaching, padding, on front and back',
	"Water smart message: Within arms' reach",
	'Water smart message: Wear a lifejacket',
	'Water smart message: Swim to Survive',
];

const PARENT_AND_TOT_2_SKILLS: SkillDescription = [
	'Entry from sitting position (assisted)',
	'Exit the water (assisted)',
	'Blow bubbles on and in water',
	'Face wet and in water',
	'Attempt to recover object below surface',
	'Entry from sitting position wearing PFD and return (assisted)',
	'Front float (face in) - assisted',
	'Back float (assisted)',
	'Kicking on front (assisted)',
	'Kicking on back (assisted)',
	'Surface passes with continous contact',
	"Water smart message: Within arms' reach",
	'Water smart message: Wear a lifejacket',
	'Water smart message: Swim to survive',
];

const PARENT_AND_TOT_3_SKILLS: SkillDescription = [
	'Jump entry (assisted)',
	'Entry and submerge from sitting position (assisted)',
	'Exit the water (unassisted)',
	'Hold breath underwater (assisted)',
	'Attempt to open eyes underwater',
	'Attempt to recover object from bottom',
	'Standing jump entry, return to edge (assisted)',
	'Jump entry and float wearing PFD (assisted)',
	'Front "starfish" float (assisted)',
	'Back "starfish" float (assisted)',
	'Front "pencil" float (assisted)',
	'Back "pencil" float (assisted)',
	'Kicking on front (assisted)',
	'Kicking on back (assisted)',
	'Underwater passes',
	"Water smart message: Within arms' reach",
	'Water smart message: Wear a lifejacket',
	'Water smart message: Swim to survive',
];

const PRESCHOOL_1_SKILLS: SkillDescription = [
	'Enter and exit shallow water (assisted)',
	'Jump into chest-deep water (assisted)',
	'Face in water',
	'blow bubbles in water',
	'Float on front (3 sec.) assisted',
	'Float on back (3 sec.) assisted',
	'Safe movement in shallow water wearing PFD',
	'Glide on front (3 m) assisted',
	'Glide on back (3 m) assisted',
	"Water smart message: Within arms' reach",
	'Water smart message: Wear a lifejacket',
];

const PRESCHOOL_2_SKILLS: SkillDescription = [
	'Enter and exit shallow water wearing PFD',
	'Jump into chest-deep water',
	'Submerge',
	'Submerge and exhale 3 times',
	'Float on front (3 sec.) wearing PFD or with buoyant aid',
	'Float on back (3 sec.) wearing PFD or with buoyant aid',
	'Roll laterally front to back and back to front, wearing PFD',
	'Glide on front (3 m) wearing PFD or with buoyant aid',
	'Glide on back (3 m) wearing PFD or with buoyant aid',
	'Flutter kick on back with buoyant aid 5 m',
	"Water smart message: Within arms' reach",
	'Water smart message: Wear a lifejacket',
];

const PRESCHOOL_3_SKILLS: SkillDescription = [
	'Jump into deep water wearing PFD, return and exit',
	'Sideways entry wearing PFD',
	'Hold breath underwater 3 sec.',
	'Submerge and exhale 5 times',
	'Recover object from bottom in waist-deep water',
	'Back float; roll to front; swim 3 m',
	'Float on front 5 sec.',
	'Float on back 5 sec.',
	'Roll laterally front to back and back to front',
	'Glide on front 3 m',
	'Glide on back 3 m',
	'Flutter kick on back 5 m',
	'Flutter kick on front 5 m',
	"Water smart message: Within arms' reach",
	'Water smart message: Wear a lifejacket',
];

const PRESCHOOL_4_SKILLS: SkillDescription = [
	'Jump into deep water, return and exit',
	'Sideways entry',
	'Tread water 10 sec. Wearing PFD',
	'Open eyes underwater',
	'Recover object from bottom in chest-deep water',
	'Wearing a PFD, sideways entry into deep water; tread 15 sec.; swim/kick 5 m',
	'Front float; roll to back; swim 5 m',
	'Glide on side 3 m',
	'Flutter kick on front 7 m',
	'Flutter kick on back 7 m',
	'Flutter kick on side 5 m',
	"Water smart message: Within arms' reach",
	'Water smart message: Wear a lifejacket',
];

const PRESCHOOL_5_SKILLS: SkillDescription = [
	'Forward roll entry wearing PFD',
	'Tread water 10 sec.',
	'Submerge and hold breath 5 sec.',
	'Recover object from bottom in chest-deep water',
	'Wearing PFD, sideways entry into deep water; tread 20 sec.; swim/kick 10 m',
	'Whip kick in vertical position 20 sec. with a PFD or buoyant aid',
	'Front crawl 5 m',
	'Back crawl 5 m',
	'Interval training: 4 x 5 m flutter kick on back with 30 sec. rests.',
	"Water smart message: Within arms' reach",
	'Water smart message: Wear a lifejacket',
];

const SWIMMER_1_SKILLS: SkillDescription = [
	'Enter and exit shallow water',
	'Jump into chest deep water',
	'Jump into water wearing PFD',
	'Tread water 30 sec. wearing PFD',
	'Hold breath underwater 5 sec.',
	'Submerge and Exhale 5 times',
	'Open eyes underwater',
	'Float on Front 5 sec.',
	'Float on Back 5 sec.',
	'Roll front to back and back to front',
	'Glide on front 3 m',
	'Glide on back 3 m',
	'Glide on side 3 m',
	'Flutter kick on front 5 m',
	'Flutter kick on back 5 m',
	'Front crawl 5 m wearing PFD',
	'Water smart message: Swim with a buddy',
	'Water smart message: Wear a lifejacket',
	'Water smart message: Check the Ice',
	'Water smart message: Swim to survive',
];

const SWIMMER_2_SKILLS: SkillDescription = [
	'Jump into deep water, return and exit',
	'Sideways entry wearing PFD',
	'Tread water 15 sec.',
	'Recover object from bottom in chest deep water',
	'Wearing PFD jump into deep water tread 30 sec. and swim/kick 15m',
	'Flutter kick on front 10 m',
	'Flutter kick on back 10 m',
	'Flutter kick on side 10 m',
	'Whip kick in vertical position 30 sec. with aid',
	'Front crawl 10 m',
	'Back crawl 10 m',
	'Interval training 4x5m flutter kick with 20s rests',
	'Water smart message: Swim with a buddy',
	'Water smart message: Wear a lifejacket',
	'Water smart message: Check the Ice',
	'Water smart message: Swim to survive',
];

const SWIMMER_3_SKILLS: SkillDescription = [
	'Kneeling dive into deep water',
	'Forward roll entry into deep water',
	'Tread water 30 sec.',
	'Handstand in shallow water',
	'Front somersault (in water)',
	'Jump into deep water, tread 30 sec., and swim/kick 25m',
	'Flutter kick on back 5 m; reverse direction and flutter kick on front 5 m',
	'Flutter kick on front 5 m; reverse direction and flutter kick on back 5 m',
	'Whip kick on back 10 m',
	'Front crawl 15 m',
	'Back crawl 15 m',
	'Interval training: 4 x 15 m flutter kick with 20 sec. rests',
	'Water smart message: Swim with a buddy',
	'Water smart message: Wear a lifejacket',
	'Water smart message: Check the Ice',
	'Water smart message: Swim to survive',
];

const SWIMMER_4_SKILLS: SkillDescription = [
	'Standing dive into deep water',
	'Tread water 1 min.',
	'Swim underwater 5 m',
	'Canadian Swim to Survive Standard: Roll entry into deep water, tread 1 min. and swim 50 m',
	'Whip kick on front 15 m',
	'Breaststroke arms drill 15 m',
	'Front crawl 25 m',
	'Back crawl 25 m',
	'Interval training: 4 x 25 m front or back crawl with 20 sec. rests',
	'Sprint front crawl 25 m',
	'Water smart message: Swim with a buddy',
	'Water smart message: Wear a lifejacket',
	'Water smart message: Check the Ice',
	'Water smart message: Swim to survive',
];

const SWIMMER_5_SKILLS: SkillDescription = [
	'Shallow dive into deep water',
	'Tuck jump (cannonball) into deep water',
	'Jump entry into deep water, and tread 2 min.',
	'Stationary eggbeater kick 30 sec.',
	'Back somersault (in water)',
	'Roll entry into deep water, tread 90 sec. and swim 75 m',
	'Breaststroke 25 m',
	'Front crawl 50 m',
	'Back crawl 50 m',
	'Head-up front crawl 10 m',
	'Interval training: 4 x 50 m front or back crawl with 30 sec. rests',
	'Interval training: 4 x 15 m breaststroke with 30 sec. rests',
	'Sprint front crawl 25 m',
	'Sprint back crawl 25 m',
	'Water smart message: Swim with a buddy',
	'Water smart message: Wear a lifejacket',
	'Water smart message: Check the Ice',
	'Water smart message: Swim to survive',
];

const SWIMMER_6_SKILLS: SkillDescription = [
	'Stride entry into deep water',
	'Compact jump into deep water',
	'Legs-only surface support 45 sec.',
	'Swim underwater 10 m to recover object',
	'Eggbeater kick on back 15 m',
	'Scissor kick 15 m',
	'Breaststroke 50 m',
	'Front crawl 100 m',
	'Back crawl 100 m',
	'Head-up swim 25 m',
	'Interval training: 4 x 25 m breaststroke with 30 sec. rests',
	'Sprint breaststroke 25 m',
	'Workout 300 m',
	'Water smart message: Swim with a buddy',
	'Water smart message: Wear a lifejacket',
	'Water smart message: Check the Ice',
	'Water smart message: Swim to survive',
];

const ROOKIE_SKILLS: SkillDescription = [
	'Head-up front crawl or breaststroke - 25 m',
	'Scull in ready position - 30 sec.',
	'Carry object (2.3 kg) - 15 m',
	'Surface dives, foot-first & head-first',
	'Lifesaving kick - 25 m',
	'Inflate clothing / use as buoyant assist',
	'Obstacle swim - 25 m',
	'Front crawl - 50 m',
	'Back crawl - 50 m',
	'Breaststroke - 50 m',
	'Fitness training: 350 m (3 times)',
	'Swim 100 m in 3 min.',
	'Assess conscious victim',
	'Contacting EMS',
	'Care for external bleeding',
	'Look & see',
	'Victim simulation',
	'Victim recognition',
	'Rescue drill: throw aid to target - 30 sec.',
];

const RANGER_SKILLS: SkillDescription = [
	'Somersault sequence, forward & backward',
	'Stride entry & swim head-up - 25 m Ready position',
	'Eggbeater kick on back - 25 m',
	'Support object (2.3kg) - 1 min.',
	'Search & recover object',
	'Remove conscious victim',
	'Front crawl - 75 m',
	'Back crawl - 75 m',
	'Breaststroke - 75 m',
	'Lifesaving medley - 100 m (3 times)',
	'Swim 200 m in 6 min.',
	'Assess unconscious, breathing victim',
	'Care for victim in shock',
	'Obstructed airway - conscious victim',
	'Victim sumulation',
	'Victim recognition',
	'Victim avoidance',
	'Rescue with buoyant aid - 20 m'
]

const STAR_SKILLS: SkillDescription = [
	'Entries with aids',
	'Head-up swim & scull in ready position',
	'Defence methods - front, side & rear',
	'eggbeater kick - travell, change direction & height',
	'Carry object (4.5 kg) - 25 m',
	'Remove unconscious victim',
	'Search to recover object',
	'Turn & support victim face-up shallow water',
	'Front crawl - 100 m',
	'Back crawl - 100 m',
	'Breaststroke - 100 m',
	'Fitness training: 600 m (3 times)',
	'Swim 300 m in 9 min.',
	'Care for bone or joint injury',
	'Care for respiratory emergency',
	'Locate & describe submerged object',
	'Rescue with towing aid - 20 m'
]

const TEEN_SKILLS: SkillDescription = [
	'Enter and exit shallow water',
	'Jump into deep water, return and exit',
	'Sideways entry wearing PFD',
	'Tread water 30 sec. wearing PFD',
	'Hold breath underwater 5-10 sec.',
	'Submerge and exhale 5-10 times',
	'Open eyes underwater',
	'Recover object from bottom in chest-deep water',
	'Wearing PFD, jump into deep water, tread 30 sec. and swim/kick on back 5-10 m',
	'Float on front',
	'Float on back',
	'Roll laterally front to back and back to front',
	'Glide on front 3-5 m',
	'Glide on back 3-5 m',
	'Glide on side 3-5 m',
	'Flutter kick on front 10-15 m',
	'Flutter kick on back 10-15 m',
	'Flutter kick on side 10-15 m',
	'Whip kick in vertical position with PFD 15-30 sec.',
	'Front crawl or back crawl 10-15 m',
	'Interval training: 4 x 9-12 m flutter kick with 10-15 sec. rests',
	'Water smart messages',
];

const ADULT_1_SKILLS: SkillDescription = [
	'Enter and exit shallow water',
	'Jump into deep water, return and exit',
	'Sideways entry wearing PFD',
	'Tread water 30 sec. wearing PFD',
	'Hold breath underwater 5-10 sec.',
	'Submerge and exhale 5-10 times',
	'Open eyes underwater',
	'Recover object from bottom in chest-deep water',
	'Wearing PFD, jump into deep water, tread 30 sec. and swim/kick on back 5-10 m',
	'Float on front',
	'Float on back',
	'Roll laterally front to back and back to front',
	'Glide on front 3-5 m',
	'Glide on back 3-5 m',
	'Glide on side 3-5 m',
	'Flutter kick on front 10-15 m',
	'Flutter kick on back 10-15 m',
	'Flutter kick on side 10-15 m',
	'Whip kick in vertical position with PFD 15-30 sec.',
	'Front crawl or back crawl 10-15 m',
	'Interval training: 4 x 9-12 m flutter kick with 10-15 sec. rests',
	'Water smart messages',
];

const ADULT_2_SKILLS: SkillDescription = [
	'Standing dive into deep water',
	'Forward roll entry into deep water with PFD',
	'Forward roll entry into deep water without PFD',
	'Tuck jump (cannonball) into deep water',
	'Tread water 1-2 min.',
	'Handstand in shallow water',
	'Front somersault (in water)',
	'Swim underwater 5-10 m',
	'Canadian Swim to Survive Standard: Roll entry into deep water, tread 1 min. and swim 50 m',
	'Flutter kick on back 5 m; reverse direction and flutter kick on front 5 m',
	'Flutter kick on front 5 m; reverse direction and flutter kick on back 5 m',
	'Whip kick on back 10-15 m',
	'Whip kick on front 10-15 m',
	'Breaststroke arms drill 10-15 m',
	'Front crawl 25-50 m',
	'Back crawl 25-50 m',
	'Interval training: 4x25 m flutter kick with 15-20 sec. rests',
	'Interval training: 4x25 m front or back crawl with 15-20 sec. rests',
	'Sprint front crawl 25 m',
	'Water smart messages',
];

const ADULT_3_SKILLS: SkillDescription = [
	'Shallow dive into deep water',
	'Stride entry into deep water',
	'Compact jump into deep water',
	'Legs-only surface support 30-60 sec.',
	'Back somersault (in water)',
	'Swim underwater 5-10 m to recover object',
	'Eggbeater kick on back or scissor kick on side 10-15 m',
	'Breaststroke 25-50 m',
	'Front crawl 50-100 m',
	'Back crawl 50-100 m',
	'Head-up front crawl 10-15 m',
	'Interval training: 4 x 50 m front or back crawl or breaststroke with 30 sec. rests',
	'Sprint (25-50 m) front crawl, back crawl, or breaststroke',
	'Workout 300m',
	'Water smart messages',
];

const FITNESS_SKILLS: SkillDescription = [
	'Pace clocks and timers',
	'Stretches for swimmers',
	'Kicking interval training',
	'Swimming interval training',
	'Workout - 300 m',
	'Workout design',
	'Distance swim',
	'Sprint swim',
]

export const WORKSHEET_SKILL_DESCRIPTIONS: SkillDescription[] = [
	PARENT_AND_TOT_1_SKILLS,
	PARENT_AND_TOT_2_SKILLS,
	PARENT_AND_TOT_3_SKILLS,
	PRESCHOOL_1_SKILLS,
	PRESCHOOL_2_SKILLS,
	PRESCHOOL_3_SKILLS,
	PRESCHOOL_4_SKILLS,
	PRESCHOOL_5_SKILLS,
	SWIMMER_1_SKILLS,
	SWIMMER_2_SKILLS,
	SWIMMER_3_SKILLS,
	SWIMMER_4_SKILLS,
	SWIMMER_5_SKILLS,
	SWIMMER_6_SKILLS,
	ROOKIE_SKILLS,
	RANGER_SKILLS,
	STAR_SKILLS,
	TEEN_SKILLS,
	ADULT_1_SKILLS,
	ADULT_2_SKILLS,
	ADULT_3_SKILLS,
	FITNESS_SKILLS,
];
