export type SkillDescription = string[];

const SWIMMER1SKILLS: SkillDescription = [
	'Enter and exit shallow water',
	'Jump into chest deep water',
	'Jump into water wearing PFD',
	'Tread water 30s wearing PFD',
	'Hold breath underwater 5s',
	'Submerge and Exhale 5 times',
	'Open eyes underwater',
	'Float on Front 5s',
	'Float on Back 5s',
	'Roll front to back and back to front',
	'Glide on front 3m',
	'Glide on back 3m',
	'Glide on side 3m',
	'Flutter kick on front 5m',
	'Flutter kick on back 5m',
	'Front crawl 5m wearing PFD',
	'Water smart message',
	'Water smart message',
	'Water smart message',
	'Water smart message',
];

const SWIMMER2SKILLS: SkillDescription = [
	'Jump into deep water, return and exit',
	'Sideways entry wearing PFD',
	'Tread water 15 sec',
	'Recover object from bottom in chest deep water',
	'Wearing PFD jump into deep water tread 30s and swim/kick 15m',
	'Flutter kick on front 10m',
	'Flutter kick on back 10m',
	'Flutter kick on side 10m',
	'Whip kick in vertical position 30s with aid',
	'Front crawl 10m',
	'Back crawl 10m',
	'Interval training 4x5m flutter kick with 20s rests',
	'Water smart message',
	'Water smart message',
	'Water smart message',
	'Water smart message',
];

export const WORKSHEET_SKILL_DESCRIPTIONS: SkillDescription[] = [
	SWIMMER1SKILLS,
	SWIMMER2SKILLS,
	SWIMMER1SKILLS,
	SWIMMER2SKILLS,
	SWIMMER1SKILLS,
	SWIMMER2SKILLS,
	SWIMMER1SKILLS,
	SWIMMER2SKILLS,
	SWIMMER1SKILLS,
	SWIMMER2SKILLS,
	SWIMMER1SKILLS,
	SWIMMER2SKILLS,
	SWIMMER1SKILLS,
	SWIMMER2SKILLS,
	SWIMMER1SKILLS,
	SWIMMER2SKILLS,
	SWIMMER1SKILLS,
	SWIMMER2SKILLS,
	SWIMMER1SKILLS,
	SWIMMER2SKILLS,
	SWIMMER2SKILLS,
];
